### PR TITLE
Revert "#417"

### PR DESCRIPTION
**Pull request by tcatapano**
Reverts cu-mkp/m-k-manuscript-data#424

### CODE REVIEW

**Comment by tcatapano** [comment]
@TillmannTaape I've reverted the merge of the previous pull request. Could you please make the changes in the branch for the issue (I believe issue417) and then submit a new pull request?

**Comment by TillmannTaape** [comment]
I've made the changes and submitted a new pull request.

**Comment by tcatapano** [comment]
Thanks @TillmannTaape Sorry for the trouble. I'll follow up on the PR tomorrow.

**Comment by TillmannTaape** [comment]
Not at all, I'm sorry I created the trouble in the first place!

**Pull request merged**
