### PR TITLE
#417

### PR DESCRIPTION
**Pull request by TillmannTaape**

### CODE REVIEW

**Comment by njr2128** [comment]
@tcatapano - can you investigate and resolve conflict?

**Comment by TillmannTaape** [comment]
Seeing as I made the changes, I resolved the conflicts to what the translation should be according to most recent protocol.

**Comment by tcatapano** [comment]
I accepted what was in the issue #417 branch, i.e.,

in tl_p006v_preTEI.xml

change to:
```when the big <tl>cane</tl> is red, they seize the hot end using```

replacing:
```when the large <tl>thin cane</tl> is red, they seize the hot end using```

and 

in tl_p066v_preTEI.xml:

change to:
```<m>card</m> folded like a small hollow cane</ms>. And putting it thus into```
replacing: 
```<m>card</m> folded up like a <sup>small hollow</sup> cane</ms>. And putting it thus into```

and

**Comment by TillmannTaape** [comment]
This is not quite correct. I thought I had resolved the conflicts, sorry if I did it incorrectly. 

6v should read:
when the large <tl>cane</tl> is red, they seize the hot end using

and 66v should read
<m>card</m> folded up like a <sup>small hollow</sup> cane</ms>. And putting it thus into

Please let me know if you'd like me to change this, and I'll do it on a new branch.

**Pull request merged**
