### PR TITLE
#1010

### PR DESCRIPTION
**Pull request by TillmannTaape**

### CODE REVIEW

**Comment by njr2128** [comment]
@TillmannTaape  here are the errors to be fixed:

- ms-xml/tl/tl_p049v_preTEI.xml:1: element root: Relax-NG validity error : Element root failed to validate attributes
- ms-xml/tl/tl_p049v_preTEI.xml:2: element page: Relax-NG validity error : Did not expect element page there
- ms-xml/tl/tl_p049v_preTEI.xml:2: element page: Relax-NG validity error : Element root failed to validate content

**Comment by tcatapano** [comment]
the tl_p049v file in this branch https://github.com/cu-mkp/m-k-manuscript-data/blob/1010/ms-xml/tl/tl_p049v_preTEI.xml seems to have been derived from a old version of this file as it does not have any attributes in it. Not sure how this happened, but it should be replaced by the current version of the file.

**Comment by TillmannTaape** [comment]
Thank you @tcatapano – how do I go about replacing them?

**Comment by tcatapano** [comment]
@TillmannTaape Maybe best to merge an then fix 49v as a separate issue. Since that file seems to be out of date, someone should read over it and verify that it is accurate according to the current specs. @njr2128 what do you think?

**Comment by njr2128** [comment]
> @TillmannTaape Maybe best to merge an then fix 49v as a separate issue. Since that file seems to be out of date, someone should read over it and verify that it is accurate according to the current specs. @njr2128 what do you think?

I think we need to go ahead with Terry's suggestion, unfortunately, which might mean more work for you, Tillmann

**Comment by TillmannTaape** [comment]
I think I've fixed it. I've checked all the changes on 49v in the original commit, and they all seemed wrong. I've pasted the tl 49v file from the master branch into the corresponding oxygen file on a new branch (issue1010c), then merged the original branch for this issue (issue1010a), then merged issue1010c with the correct 49v TL file.

**Pull request merged**
